export const categoriesEnum = [
  "Hindu temple",
  "Spiritist center",
  "Place of worship",
  "Tourist attraction",
  "Museum",
  "Park",
  "Garden",
  "Nature preserve",
  "Hiking area",
  "Community garden",
  "Memorial park",
  "Jain temple",
  "Lake",
  "Historical landmark",
  "War memorial",
  "City park",
  "Government office",
  "Flower market",
  "Historical place",
  "Religious organization",
  "Miniatures store",
];
