export const hotelEnum = [
  "Hotel",
  "Bed & breakfast",
  "Lodge",
  "Serviced accommodation",
  "Meeting planning service",
  "Wedding venue",
  "Banquet hall",
  "Bar",
  "Conference center",
  "Restaurant",
  "Extended stay hotel",
  "Indoor lodging",
  "Gym",
  "Spa",
  "Swimming pool",
  "Holiday home",
  "Homestay",
  "Serviced apartment",
  "Guest house",
  "Holiday apartment rental",
  "Resort hotel",
  "Business center",
  "Event venue",
  "Lodging",
  "Farmstay",
  "Inn",
  "Student dormitory",
  "Tour operator",
  "Tourist attraction",
  "Travel agency",
  "Hostel",
  "Concert hall",
  "Caterer",
  "Party planner",
  "Wedding planner",
  "Boutique",
  "Wellness hotel",
  "Buffet restaurant",
  "Fine dining restaurant",
  "Coworking space",
  "Youth hostel",
  "Motel",
  "Cafe",
  "Tour agency",
  "Seafood restaurant",
  "South Indian restaurant",
  "Childrens party buffet",
  "Wedding buffet",
  "Family restaurant",
  "Gymnastics club",
  "Airline",
  "Sightseeing tour agency",
  "Movie theater",
  "Holiday apartment",
  "Vegetarian restaurant",
  "Laundry service",
];